# Generated by Django 4.0.4 on 2022-06-15 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('phone_number', models.BigIntegerField(unique=True)),
                ('language', models.CharField(choices=[('AR', 'Arabic'), ('CHI', 'Chinese'), ('ENG', 'English'), ('FRA', 'French'), ('GER', 'German'), ('HIN', 'Hindi'), ('JPN', 'Japanese'), ('SPA', 'Spanish')], max_length=3)),
                ('currency', models.CharField(choices=[('CNY', 'Chinese Yuan'), ('EUR', 'Euro'), ('GBP', 'Pound'), ('INR', 'Indian Rupee'), ('JPY', 'Japanese Yen'), ('NGN', 'Nigerian Naira'), ('USD', 'US Dollar')], max_length=3)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('area', models.TextField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mozio_library.provider')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
