# Generated by Django 4.0.4 on 2022-06-15 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mozio_library', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicearea',
            old_name='area',
            new_name='poly',
        ),
    ]
